<?php defined('IN_CMS') or die('No direct access allowed.');

return array(

'posts' => 'Entradas',
'create_post' => 'Agregar una Entrada',
'created' => 'Creado el',
'create' => 'Crear',
'by' => 'por',
'noposts' => 'No tienes entradas hasta ahora. Porque no escribes una?',
'return_posts' => 'Regresar a entradas',

'add_post' => 'Agregar una entrada',
'post' => 'Entrada',
'customise' => 'Personalizar',
'customise_explain' => 'Aqui puedes personalizar tus entradas. Esto es opcional.',
'custom_fields' => 'Campos especiales.',
'custom_fields_explain' => 'Crea tus campos especiales aqui.',
'create_custom_field' => 'Crea un campo especial',
'comments' => 'Comentarios',
'comments_explain' => 'Aqui puedes moderar los comentarios de tu pagina.',
'no_comments' => 'Sin Comentarios',
'edit_comment' => 'Editar Comentario',
'edit_comment_explain' => 'Actualiza el comentario aqui.',

'publish' => 'Publicar',
'edit' => 'Editar',
'delete' => 'Borrar',
'save' => 'Guardar',
'label' => 'Etiqueta',
'key' => 'Palabra Clave',
'editing' => 'Editando',
'editing_explain' => 'Algunos enlaces de interes.',
'view_post' => 'Visualiza esta entrada en tu pagina.',

'draft' => 'Borrador',
'archived' => 'Archivado',
'published' => 'Publicado',
'pending' => 'Pendiente',
'spam' => 'Spam',
'update' => 'Actualizar',
'close' => 'Cerrar',

'custom_field' => 'Campo Special',
'custom_field_explain' => 'Introduce el nombre y la key de tu campo',
'missing_label' => 'Introduce una etiqueta para el campo',
'missing_key' => 'Introduce la palabra clave del campo.',

'title' => 'Titulo',
'title_explain' => 'El titulo de tu entrada',
'slug' => 'Slug',
'slug_explain' => 'The slug for your post (<code id="output">slug</code>).',
'description' => 'Descripción',
'description_explain' => 'Un breve resumen de tu entrada. Es usado por los RSS Feeds.',
'content' => 'Contenido',
'content_explain' => 'El contenido de tu entrada. Puede disfrutar de una buena dosis de HTML.',
'status' => 'Estado',
'status_explain' => 'Estados: Publicado, Pendiente (borrador), or Oculto (archivado).',
'allow_comments' => 'Permitir comentarios',
'allow_comments_explain' => 'Esto permitira a los usuarios dejar comentarios en tus entradas.',
'custom_css' => 'CSS Personalizado',
'custom_css_explain' => 'Tu CSS Personalizado. Será encerrado dentro de un bloque de codigo. (<code>&lt;code&gt;</code>)',
'custom_js' => 'JS Personalizado',
'custom_js_explain' => 'Tu JavaScript Personalizado. Será encerrado dentro de un bloque de codigo. (<code>&lt;script&gt;</code>)',

'missing_title' => 'Introduce un titulo.',
'missing_description' => 'Introduce una descripción',
'missing_html' => 'Introduce tu HTML',
'duplicate_slug' => 'Ya se ha realizado una entrada con el mismo slug. Por favor, intenta otro.',
'post_success_created' => 'Se ha agregado tu nueva entrada.',
'post_success_updated' => 'Tu entrada ha sido actualizada',
'post_success_deleted' => 'Se ha eliminado la entrada'

);